Optimizer:
    name: 'torch.optim.Adam'
    lr: 1.0e-4

Dataset:
  data_path: 'data/worldclim2.zarr'
  points_path: '../coordinates.h5'
  normalised_stats_path: '../normalized_stats.json'
  data_key: 'land_coords' # 'ocean_coords'
  shuffle: True



Model:
  SIREN_MODEL:
    name: 'models.implicit_neural_representations.inr_models.siren_model.SirenModel'
    in_features: 2
    out_features: 2
    hidden_layers: 5
    hidden_features: 128
    bias: True
    final_bias: False
    first_omega_0: 30.0
    hidden_omega_0: 30.0
    residual_net: False # set true is using siren residual model
    encoding: None # 'dfs' or 'sphere2vec' or none
    r_min : 0.001
    r_max : 1.0
    scale: [10, 10] # [scale_lat, scale_lon] for dfs,  int for sphere2vec
    mode: "SphereC" # for basic sphere2vec, "SphereM" for multi-scale sphere2vec

  FINER_MODEL:
    name: 'models.implicit_neural_representations.inr_models.siren_model.FinerModel'
    in_features: 2
    out_features: 2
    hidden_layers: 5
    hidden_features: 128
    bias: True
    final_bias: False
    first_omega_0: 30.0
    hidden_omega_0: 30.0  # scaling factor
    first_k: 1.0 # higher bias values give large range of frequencies
    hidden_k: 1.0
    residual_net: False # set true is using finer residual model
    encoding: None # 'dfs' or 'sphere2vec' or none
    r_min : 0.001
    r_max : 1.0
    scale: [10, 10] # [scale_lat, scale_lon] for dfs,  int for sphere2vec
    mode: "SphereC" # for basic sphere2vec, "SphereM" for multi-scale sphere2vec
